### ISSUE TITLE
Add option on SlicedData-Tab to transpose the plotdata-array

### ISSUE THREAD

**Issue by peterpuschnig** [brands-d/kMap#13]
It would be convenient to have the possibility to transpose the data shown on the SlicedData-Tab, that is, interchange the x-and y-axes. For instance, on the example4 and example5 datasets, the kx-axis is vertical and the ky-axis is horizontal. For instance, with a check-box "transpose" kx and ky should be interchanged.

**Comment by brands-d** [comment]
Addressed in commit 00d707d.

**Comment by peterpuschnig** [comment]
That's exactly what I had in mind, thanks!
