### ISSUE TITLE
Enable plot of CrossHair Intensity (Point, Area or Annulus) vs. slices

### ISSUE THREAD

**Issue by peterpuschnig** [brands-d/kMap#22]
On the SlicedData-Tab it would be nice to enable plotting of the Crosshaur-Intensity values, that is, either Point or Area or Annulus, as a function of the slice number (e.g. kinetic energy).

**Comment by brands-d** [comment]
Addressed in commit 239ff24. Waiting for user tests and feedback before closing the issue.

**Comment by peterpuschnig** [comment]
The new option "slice like plot" on the Profile-Tab works well and solves this issue!
