### ISSUE TITLE
Negative Values for |A.k|^2

### ISSUE THREAD

**Issue by brands-d** [brands-d/kMap#47]
Low angles of incidence can lead to negative values in the polarisation factor |A.k|^2 for the Nano-ESCA: He-lamp.

**Comment by peterpuschnig** [comment]
The problem has been fixed in the commit 114ae81 on the "Peter" branch.

**Comment by brands-d** [comment]
The s_share setting implemented in the last fix is now changeable in the general settings file and will be respected throughout the program. For more information please see commit message (7f2e6eb)
